language: go
go:
- 1.13.x
env:
- CGO_ENABLED=0
dist: xenial
before_script:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go test -coverprofile=coverage.cov -coverpkg=./... ./...
- $GOPATH/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
