language: go
go:
- 1.12.x
env:
- CGO_ENABLED=0
dist: xenial
before_script:
- GO111MODULES=on go get golang.org/x/tools/cmd/cover
- GO111MODULES=on go get github.com/mattn/goveralls
script:
- GO111MODULES=on go test -coverprofile=coverage.cov -coverpkg=./... ./...
- $GOPATH/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
before_install:
- openssl aes-256-cbc -K $encrypted_bfb3eaa23890_key -iv $encrypted_bfb3eaa23890_iv
  -in testdata/psiphon_config.json.enc -out testdata/psiphon_config.json -d
