// Code generated by go generate; DO NOT EDIT.
// Generated on: 2021-01-25 08:44:21.943695 +0100 CET m=+0.025302555

package ooniapi

import (
	"context"

	"github.com/ooni/probe-engine/ooniapi/ooniapimodel"
)

//go:generate go run ./gocompiler

// GETCheckReportID implements the GET /api/_/check_report_id API
func (c Client) GETCheckReportID(ctx context.Context, req *ooniapimodel.CheckReportIDRequest) (*ooniapimodel.CheckReportIDResponse, error) {
	var out ooniapimodel.CheckReportIDResponse
	err := c.api(ctx, apispec{
		Method:  "GET",
		URLPath: "/api/_/check_report_id",
		In:      req,
		Out:     &out,
	})
	return &out, err
}

// GETMeasurementMeta implements the GET /api/v1/measurement_meta API
func (c Client) GETMeasurementMeta(ctx context.Context, req *ooniapimodel.MeasurementMetaRequest) (*ooniapimodel.MeasurementMetaResponse, error) {
	var out ooniapimodel.MeasurementMetaResponse
	err := c.api(ctx, apispec{
		Method:  "GET",
		URLPath: "/api/v1/measurement_meta",
		In:      req,
		Out:     &out,
	})
	return &out, err
}

// POSTOpenReport implements the POST /report API
func (c Client) POSTOpenReport(ctx context.Context, req *ooniapimodel.OpenReportRequest) (*ooniapimodel.OpenReportResponse, error) {
	var out ooniapimodel.OpenReportResponse
	err := c.api(ctx, apispec{
		Method:  "POST",
		URLPath: "/report",
		In:      req,
		Out:     &out,
	})
	return &out, err
}

// POSTSubmitMeasurement implements the POST /report/{report_id} API
func (c Client) POSTSubmitMeasurement(ctx context.Context, req *ooniapimodel.SubmitMeasurementRequest) (*ooniapimodel.SubmitMeasurementResponse, error) {
	var out ooniapimodel.SubmitMeasurementResponse
	err := c.api(ctx, apispec{
		Method:  "POST",
		URLPath: "/report/{report_id}",
		In:      req,
		Out:     &out,
	})
	return &out, err
}

// GETTestHelpers implements the GET /api/v1/test-helpers API
func (c Client) GETTestHelpers(ctx context.Context, req *ooniapimodel.TestHelpersRequest) (*ooniapimodel.TestHelpersResponse, error) {
	var out ooniapimodel.TestHelpersResponse
	err := c.api(ctx, apispec{
		Method:  "GET",
		URLPath: "/api/v1/test-helpers",
		In:      req,
		Out:     &out,
	})
	return &out, err
}

// GETURLS implements the GET /api/v1/test-list/urls API
func (c Client) GETURLS(ctx context.Context, req *ooniapimodel.URLSRequest) (*ooniapimodel.URLSResponse, error) {
	var out ooniapimodel.URLSResponse
	err := c.api(ctx, apispec{
		Method:  "GET",
		URLPath: "/api/v1/test-list/urls",
		In:      req,
		Out:     &out,
	})
	return &out, err
}
