name: cli-linux
on: [push]
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ["1.14"]
    steps:
      - uses: actions/checkout@v2
      - run: ./build-cli.sh linux
      - uses: actions/upload-artifact@v1
        with:
          name: miniooni-linux-amd64
          path: ./CLI/linux/amd64/miniooni
