name: cli-darwin
on: [push]
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        go: ["1.14"]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: ./build-cli.sh darwin
      - uses: actions/upload-artifact@v1
        with:
          name: miniooni-darwin-amd64
          path: ./CLI/darwin/amd64/miniooni
