name: cli
on: [push]
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        go: ["1.14"]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: brew install mingw-w64 zip
      - run: ./build-cli.bash darwin
      - run: tar -cvzf darwin.tgz ./CLI/darwin
      - run: ./build-cli.bash windows
      - run: zip -r windows.zip ./CLI/windows
      - uses: actions/upload-artifact@v1
        with:
          name: darwin.tgz
          path: ./darwin.tgz
      - uses: actions/upload-artifact@v1
        with:
          name: windows.zip
          path: ./windows.zip
