name: golang
on:
  push:
  pull_request:
  schedule:
    - cron: "14 17 * * 3"
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ["1.14"]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: go test -tags shaping -v -coverprofile=probe-engine.cov -coverpkg=./... ./...
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: probe-engine.cov
          parallel: true
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
