name: ios
on:
  push:
    branches:
      - mobile-staging
      - 'release/**'
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: ./build-ios.bash
      - run: ./publish-ios.bash
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
