name: jafar
on: [push]
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ["1.14"]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: go build -v ./cmd/jafar
      - run: sudo ./testjafar.bash
