name: libooniffi
on:
  schedule:
    - cron: "0 5 * * 3"
jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: ./libooniffi/buildtest.bash darwin
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: ./libooniffi/buildtest.bash linux
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: bash.exe ./libooniffi/buildtest.bash windows
