name: miniooni
on:
  push:
    branches:
      - 'release/**'
  schedule:
    - cron: "0 0 * * */1"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2

      - run: ./build-cli.sh linux
      - run: ./CLI/linux/amd64/miniooni --yes -nNi https://example.com web_connectivity
      - uses: actions/upload-artifact@v1
        with:
          name: miniooni-linux-386
          path: ./CLI/linux/386/miniooni
      - uses: actions/upload-artifact@v1
        with:
          name: miniooni-linux-amd64
          path: ./CLI/linux/amd64/miniooni
      - uses: actions/upload-artifact@v1
        with:
          name: miniooni-linux-armv7
          path: ./CLI/linux/armv7/miniooni
      - uses: actions/upload-artifact@v1
        with:
          name: miniooni-linux-arm64
          path: ./CLI/linux/arm64/miniooni

      - run: ./build-cli.sh darwin
      - uses: actions/upload-artifact@v1
        with:
          name: miniooni-darwin-amd64
          path: ./CLI/darwin/amd64/miniooni

      - run: sudo apt install --yes mingw-w64
      - run: ./build-cli.sh windows
      - uses: actions/upload-artifact@v1
        with:
          name: miniooni-windows-amd64.exe
          path: ./CLI/windows/amd64/miniooni.exe
