name: mk
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - container:
          image: openobservatory/mk-alpine:latest
        run: |
          apk add --no-progress git go
          go test -v -race ./...
