name: qa
on: [push]
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ["1.14"]
        experiment: ["fbmessenger", "telegram", "whatsapp"]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: ./QA/rundocker.bash ${{ matrix.experiment }}
