name: qa
on:
  push:
  schedule:
    - cron: "14 17 * * 3"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        experiment: ["fbmessenger", "hhfm", "hirl", "telegram", "webconnectivity", "whatsapp"]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: ./QA/rundocker.bash ${{ matrix.experiment }}
